name: EKS Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: install awscli
              uses: aws-actions/configure-aws-credentials@v5.0.0
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: Setup kubectl
              uses: azure/setup-kubectl@v4
              with:
                  version: "latest"
            - name: Update kubeconfig
              run: |
                  aws eks update-kubeconfig --name=demo-eks-cluster --region=us-east-1

            - name: Deploy to EKS
              run: |
                  kubectl apply -f k8s/app.yaml
