name: demo-CI/CD on github-actions - terraform

on:
  push:
    branches:
      - main

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: clone the code
        uses: actions/checkout@v3
      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.3"
      - name: configure aws access
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: init terraform
        run: |
          echo "running terraform init"
          terraform init
      - name: plan terraform
        run: |
          echo "running terraform plan"
          terraform plan
      - name: apply terraform
        run: |
          echo "applying terraform"
          terraform apply --auto-approve
